from selenium.webdriver.common.by import By

button_bags = (By.LINK_TEXT, 'Bags')
sort_items = (By.CSS_SELECTOR, 'a[id="mode-list"]')
button_style_selection = (By.XPATH, '//div[@class="filter-options-title" and @data-role="title"]')
button_style_selection_duffel = (By.PARTIAL_LINK_TEXT, 'Duffel')
check_that_product_items = (By.CSS_SELECTOR, 'ol[class="products list items product-items"]')
add_product = (By.XPATH, '//button[@type="submit" and @title="Add to Cart"]')
click_cart = (By.CSS_SELECTOR, 'a[class="action showcart"]')
cart = (By.CSS_SELECTOR, 'div[class="minicart-items-wrapper"]')
remove_items = (By.XPATH, '//a[@class="action delete" and @title="Remove item"]')
no_items_in_cart = (By.CSS_SELECTOR, 'div[id="minicart-content-wrapper"]')
accept_alert = (By.CSS_SELECTOR, 'button[class="action-primary action-accept"]')
button_watches = (By.LINK_TEXT, 'Watches')
watches_product_selection = (By.CSS_SELECTOR, 'li[class="item product product-item"]')
watches_action_to_compare = (By.CSS_SELECTOR, 'a[class="action tocompare"]')
check_that_block_compare = (By.CSS_SELECTOR, '//div[@role="alert" and @class="messages"]')
button_clear_compare = (By.CSS_SELECTOR, 'a[id="compare-clear-all"]')
button_accept_clear_compare = (By.CSS_SELECTOR, 'button[class="action-primary action-accept"]')
check_that_compare_clear = (By.CSS_SELECTOR, 'div[class="empty"]')
message_clear_in_compare = (By.XPATH, '//div[@role="alert" and @class="messages"]')
button_fit_euip = (By.LINK_TEXT, 'Fitness Equipment')
button_add_product_to_wish_list = (By.CSS_SELECTOR, 'a[class="action towishlist"]')
check_added_product_to_wish_list = (By.XPATH, '//div[@role="alert" and @class="messages"]')
button_remove_from_wish_list = (By.XPATH, '//a[@title="Remove This Item"]')
message_no_items_in_wish_list = (By.XPATH, '//div[@role="alert" and @class="messages"]')
move_to_product_wish_list = (By.CSS_SELECTOR, 'div[class="product-item-info"]')
check_that_added_product_in_cart = (By.CSS_SELECTOR, '//div[@role="alert" and @class="messages"]')
