from selenium.webdriver.common.by import By

button_men = (By.CSS_SELECTOR, 'a[id="ui-id-5"]')
button_tops = (By.CSS_SELECTOR, 'a[id="ui-id-17"]')
button_jackets = (By.CSS_SELECTOR, 'a[id="ui-id-19"]')
button_sort_items = (By.CSS_SELECTOR, 'a[id="mode-list"]')
button_size_selection = (By.CSS_SELECTOR, 'div[id="option-label-size-143-item-167"]')
button_color_selection = (By.CSS_SELECTOR, 'div[id="option-label-color-93-item-49"]')
button_add_product_to_cart = (By.CSS_SELECTOR, 'button[class="action tocart primary"]')
button_cart = (By.CSS_SELECTOR, 'a[class="action showcart"]')
button_proceed_to_checkout = (By.XPATH, '//button[@id="top-cart-btn-checkout"]')
button_next = (By.CSS_SELECTOR, 'button[class="button action continue primary"]')
button_view_items = (By.XPATH, '//div[@class="block items-in-cart"]')
button_view_details = (By.XPATH, '//div[@class="product options"]')
button_place_order = (By.CSS_SELECTOR, 'button[class="action primary checkout"]')
check_products_per_page = (By.CSS_SELECTOR, 'p[class="toolbar-amount"]')
check_that_items_in_cart = (By.CSS_SELECTOR, 'div[class="items-total"]')
check_name_last_name = (By.CSS_SELECTOR, 'div[class="shipping-address-item selected-item"]')
check_that_product_name_block = (By.CSS_SELECTOR, 'div[class="product-item-name-block"]')
check_product_size = (By.CSS_SELECTOR, 'dd[class="values"]')
check_product_color = (By.CSS_SELECTOR, 'dd[class="values"]')
check_product_details = (By.XPATH, '//dl[@class="item-options"]')
check_product_details_titles = (By.TAG_NAME, 'dt')
check_product_details_values = (By.TAG_NAME, 'dd')
check_that_place_order_continue = (By.CSS_SELECTOR, 'div[class="checkout-success"]')
